server:
  port: 8087
spring:
  cloud:
    config:
      server:
        git:
          default-label: servicios
          uri: https://github.com/GustafffSoft/gateway
          search-paths: config-data
  application:
    name: config-service
